CREATE TABLE CGV(
	CID INT PRIMARY KEY, -- 기본키
	TITLE VARCHAR(100) NOT NULL, --영화제목
	IMAGE VARCHAR(1000) NOT NULL, --
	GENRE VARCHAR(100),
	BOOKCNT INT DEFAULT 0
);

SELECT * FROM CGV;
SELECT * FROM USER_TABLES;
DROP TABLE CGV;
DROP TABLE MEMBER;
DROP TABLE BOOK;

UPDATE CGV SET BOOKCNT=BOOKCNT+1  WHERE CID=5;

SELECT * FROM CGV WHERE TITLE LIKE '%%' OR GENRE LIKE '%%' ORDER BY CID ASC;

CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(100) NOT NULL,
	MNAME VARCHAR(50) NOT NULL,
	MBOOK VARCHAR(2000) 
);

CREATE TABLE BOOK(
	BID INT PRIMARY KEY,
	CID INT,
	MID VARCHAR(20)
);



INSERT INTO MEMBER VALUES('amlsn1','민우','1234');
INSERT INTO MEMBER VALUES('관리자', '1234', '관리자', null);
DELETE FROM MEMBER WHERE MID='amlsn1' AND MPW='1235';
SELECT * FROM MEMBER;
DROP TABLE MEMBER;
	
	
	
	
	